/* Architecture content is kept separate from rendering and interaction. */
window.STACK_LAYERS = Object.freeze([
  {
    number: '01', category: 'Het fundament', short: 'Goed geregeld', nav: 'Goed geregeld',
    title: 'Verantwoord starten. Samen goed geregeld.',
    description: 'Kies je voor Limescape, dan helpen we je om AI verantwoord in te zetten. Samen zorgen we voor duidelijke afspraken over wetgeving, veiligheid, privacy en kwaliteit, passend bij jouw organisatie.',
    icon: 'shield',
    technologies: ['EU AI Act', 'GDPR / AVG', 'TrueLime · ISO 9001', 'TrueLime · ISO 27001'],
    principle: 'Verantwoord werken begint bij het ontwerp en groeit mee met het gebruik. We verbinden mensen, afspraken en ondersteuning tot een stevig fundament.',
    focus: 'Vanaf de start goed geregeld',
  },
  {
    number: '02', category: 'Jouw omgeving', short: 'Jouw omgeving', nav: 'Jouw omgeving',
    title: 'Limescape waar jij het wilt.',
    description: 'Laat Limescape door ons hosten in Microsoft Azure, kies Private SaaS bij jouw cloudprovider of draai het volledig self-hosted in je eigen omgeving. Jij kiest wat past bij jouw organisatie.',
    icon: 'server',
    technologies: ['SaaS in Microsoft Azure', 'Private SaaS', 'Volledig self-hosted'],
    principle: 'Moderne, vertrouwde technologie geeft je de vrijheid om te kiezen waar Limescape draait. Samen spreken we af wie het beheer, onderhoud en de beveiliging verzorgt.',
    focus: 'Vrijheid in waar je werkt',
  },
  {
    number: '03', category: 'Jouw kennis', short: 'Jouw kennis', nav: 'Jouw kennis',
    title: 'De kennis van jouw organisatie. Binnen handbereik.',
    description: 'Maak documenten, werkinstructies en andere vertrouwde informatie bruikbaar voor je medewerkers. Limescape helpt hen relevante kennis te vinden en toe te passen in hun dagelijkse werk.',
    icon: 'data',
    technologies: ['Eigen informatie', 'Relevante antwoorden', 'Toegang op maat'],
    principle: 'Jouw kennis is het vertrekpunt. Samen bepalen we welke informatie gebruikt mag worden en voor wie die beschikbaar is.',
    focus: 'Van organisatiekennis naar bruikbaar inzicht',
  },
  {
    number: '04', category: 'Inzicht & verantwoording', short: 'Inzicht & uitleg', nav: 'Inzicht & verantwoording',
    title: 'Meten is weten. Vanaf het ontwerp.',
    description: 'Wij werken altijd vanuit evals-by-design: vanaf het ontwerp toetsen we of AI doet wat jouw organisatie nodig heeft. We meten kwaliteit, veiligheid en prestaties bij groeiend gebruik. Samen met uitlegbare antwoorden en vastgelegde controles vormt dat de basis voor werkende, schaalbare en veilige AI-oplossingen.',
    icon: 'trace',
    technologies: ['Evals-by-design', 'Uitlegbare antwoorden', 'Aantoonbare verantwoording'],
    principle: 'We spreken vooraf af wat goed genoeg is en toetsen vóór ingebruikname en bij iedere wijziging opnieuw. De resultaten helpen je om verantwoord te kiezen, bij te sturen en de afspraken uit het fundament aantoonbaar na te leven.',
    focus: 'Meten, begrijpen en verantwoorden',
  },
  {
    number: '05', category: 'De praktijk · de top', short: 'Jouw werk', nav: 'Jouw werk',
    title: 'Meer ruimte voor het werk dat ertoe doet.',
    description: 'Vind sneller informatie, handel terugkerende vragen af en verminder handmatig werk. Limescape helpt jouw medewerkers in hun dagelijkse praktijk, met menselijke beoordeling waar die nodig is.',
    icon: 'person',
    technologies: ['Minder herhaalwerk', 'Sneller antwoord', 'Menselijke regie'],
    principle: 'AI ondersteunt de professional. De mens beoordeelt, houdt toezicht en behoudt de beslissingsbevoegdheid.',
    focus: 'Van betrouwbare basis naar waarde in de praktijk',
  },
].map((layer, index) => ({
  ...layer,
  color: getComputedStyle(document.documentElement).getPropertyValue(`--layer-${index + 1}`).trim(),
})));
